### ISSUE TITLE
ServerURL has to start with www

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/carto.js#2198] opened 2018-09-18 07:35 UTC
### Context
See issue #2197 for context.

Apparently, we force that serverUrl has to start with `www`, so the users can't set an IP address, for example.

- [ ] Check if this is happening.
- [ ] If it's true, fix the RegEx to allow IP addresses as well.

**Comment by IagoLast** [comment] 2018-09-18 08:33
the problem is our urls require an username, for example

https://ivanmalagon.carto.com is valid

how do we manage this with ip adresses?

**Comment by Jesus89** [comment] 2018-10-17 15:16
> ServerURL has to start with www

This is not true. For example `https://USER.carto.com` is a perfectly valid user without www.

There is an issue with the docs because

```

**Comment by Jesus89** [comment] 2018-10-17 15:19
1. Do we want to allow URL addresses using `{user}` like `https://{user}.carto.com`?
2. The docs should be fixed
3. In order to use an IP address, the common way is to set up the /etc/hosts file with a name for the API (or the equivalent for other OS)

**Comment by Jesus89** [comment] 2018-10-18 08:52
Closed by https://github.com/CartoDB/carto.js/pull/2203

In production! :rocket:

**Closed by Jesus89** 2018-10-18 08:52 UTC
Labels: bug
